// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs1_RGld8p4DBLrHi7pXWSOHmHWHcjwyk',
    appId: '1:96588103250:ios:deb9dc187852e20233298b',
    messagingSenderId: '96588103250',
    projectId: 'seva-setu-8991c',
    storageBucket: 'seva-setu-8991c.firebasestorage.app',
    iosClientId: '96588103250-cbreho4b9va2de3c2opreoo06il0kig4.apps.googleusercontent.com',
    iosBundleId: 'com.grievance.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs1_RGld8p4DBLrHi7pXWSOHmHWHcjwyk',
    appId: '1:96588103250:ios:deb9dc187852e20233298b',
    messagingSenderId: '96588103250',
    projectId: 'seva-setu-8991c',
    storageBucket: 'seva-setu-8991c.firebasestorage.app',
    iosClientId: '96588103250-cbreho4b9va2de3c2opreoo06il0kig4.apps.googleusercontent.com',
    iosBundleId: 'com.grievance.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYQtFBccklHNszPVcWIPxX1QckgUjKWi4',
    appId: '1:96588103250:web:75abd7a57230c42c33298b',
    messagingSenderId: '96588103250',
    projectId: 'seva-setu-8991c',
    authDomain: 'seva-setu-8991c.firebaseapp.com',
    storageBucket: 'seva-setu-8991c.firebasestorage.app',
    measurementId: 'G-H1TKJHE64H',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYQtFBccklHNszPVcWIPxX1QckgUjKWi4',
    appId: '1:96588103250:web:21e9949c2a19099233298b',
    messagingSenderId: '96588103250',
    projectId: 'seva-setu-8991c',
    authDomain: 'seva-setu-8991c.firebaseapp.com',
    storageBucket: 'seva-setu-8991c.firebasestorage.app',
    measurementId: 'G-9RWF5LKZM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3iK0-VoIGofSB6_4vNiIp0taWMdj5BOU',
    appId: '1:96588103250:android:3b122b541b1a34d833298b',
    messagingSenderId: '96588103250',
    projectId: 'seva-setu-8991c',
    storageBucket: 'seva-setu-8991c.firebasestorage.app',
  );

}